### ISSUE TITLE
Upgrade to preprocess 3.0.2

### ISSUE THREAD

**Issue by Alphapage** [dearrrfish/preprocess-loader#2]
Hello,

Could you upgrade to latest preprocess version ?

Thanks in advance.

**Comment by Alphapage** [comment]
It would be great to remove peerdependency because it is depreciated in npm3.

**Comment by dearrrfish** [comment]
@Alphapage Thanks for feedback. Please upgrade to latest version.

**Comment by Alphapage** [comment]
Perfect.
Thank you very much
