### ISSUE TITLE
ERROR in Loader project\node_modules\preprocess\lib\preprocess.js didn't return a function

### ISSUE THREAD

**Issue by flyon** [dearrrfish/preprocess-loader#5]
I did 

    npm install --save preprocess

and in webpack 

    module: {
        loaders: [
            {test: /\.tsx?$/,loader: "preprocess!ts-loader"}
        ],

but webpack says:

     ERROR in Loader F:\wamp-new\www\dacore\modules\browser-core\node_modules\preprocess\lib\preprocess.js didn't return a function

using webpack 1.13. Will try upgrading to webpack 2 now

Edit: similar error with webpack 2:

    Error: Module 'F:\wamp-new\www\dacore\modules\browser-core\node_modules\preprocess\lib\preprocess.js' is not a loader (must have normal or pitch function)

**Comment by scholtzm** [comment]
You have most likely solved this by now but for completeness sake, you need to install `preprocess-loader` not `preprocess`.
